#! /bin/bash

set -eu

ERROR="$(basename $0) ERROR"

configure_package_builder_group()
{
    if ! getent group package-builder &> /dev/null; then
        addgroup --quiet --system package-builder
    fi

    if getent group sudo &> /dev/null; then
        for user in $(members sudo); do
            adduser --quiet "$user" package-builder
        done
    fi
}

if [[ "$1" = "configure" ]]; then
    if ! which pbt; then
        echo "${ERROR} - could not find pbt" 1>&2
        exit 1
    fi

    activate_python_argcomplete=$(find /usr/bin -name "activate-global-python-argcomplete*" 2>/dev/null | head -1)
    register_python_argcomplete=$(find /usr/bin -name "register-python-argcomplete*" 2>/dev/null | head -1)
    $activate_python_argcomplete --dest /usr/share/bash-completion/completions/
    $register_python_argcomplete pbt \
        > /usr/share/bash-completion/completions/pbt

    configure_package_builder_group
fi

set +eu

#DEBHELPER#
