#! /bin/bash

set -eu

ERROR="$(basename $0) ERROR"

configure_package_builder_group()
{
    if ! getent group package-builder &> /dev/null; then
        addgroup --quiet --system package-builder
    fi

    if getent group sudo &> /dev/null; then
        for user in $(members sudo); do
            adduser --quiet "$user" package-builder
        done
    fi
}

if [[ "$1" = "configure" ]]; then
    if ! which pbt; then
        echo "${ERROR} - could not find pbt" 1>&2
        exit 1
    fi

    activate-global-python-argcomplete3 --dest /usr/share/bash-completion/completions/
    register-python-argcomplete3 pbt \
        > /usr/share/bash-completion/completions/pbt

    configure_package_builder_group
fi

set +eu

#DEBHELPER#
